---
- hosts: staging
  become: true
  tasks:
  - debug:
      var: ansible_os_family
  - name: Docker login {{DOCKER_REGISTRY}}
    command: docker login -u {{DOCKER_USERNAME}} -p "{{DOCKER_PASSWORD}}" registry.d2t.vn

  - name: Stop container old
    command: docker rm -f {{DOCKER_IMAGE}}

  - name: Start the container
    command: docker run --rm -p 9999:80 --name {{DOCKER_IMAGE}} -d {{DOCKER_REGISTRY}}/{{DOCKER_IMAGE}}:{{DOCKER_TAG}}
