---
- hosts: staging
  become: true
  tasks:
  - debug:
      var: ansible_os_family
      
  - name: "create yum repository for docker"
    yum_repository:
      name: docker-repo
      description: "repo for docker"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      enabled: yes
      gpgcheck: no
    when: ansible_facts['os_family'] == 'RedHat'
  
  - name: "Install docker"
    package: 
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present

  - name: "Install pip"
    package: 
      name: "python3-pip"
      state: present
      update_cache: true

  - name: "Install python-setuptools"
    package: 
      name: "python-setuptools"
      state: present
      update_cache: true
    
  - name: "Install docker sdk"
    pip:
     name: "docker"
 
  - name: "Start docker service"
    service:
      name: "docker"
      state: started

  - name: Docker login registry.d2t.vn
    command: docker login -u duonghongthuan -p "abc123^%$" registry.d2t.vn

  - name: Stop container old
    command: docker rm -f laravel-ansible-docker

  - name: Start the container
    command: docker run --rm -p 9999:80 --name laravel-ansible-docker -d registry.d2t.vn/laravel-ansible-docker:master-d7bc3bc
