---

- hosts: staging
  tasks:
    - name: "repository"
      yum_repository:
        name: "Docker"
        description: "Docker Repo"
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
        gpgcheck: "no"
    - name: "installing docker package"
      command: "yum install docker-ce --nobest -y"
    - name: "Starting docker service"
      service:
        name: "docker"
        state: started
        enabled: yes
    - command: "pip3 install docker"
    - name: Docker login registry.d2t.vn
      docker_login:
        registry: registry.d2t.vn
        username: duonghongthuan
        password: abc123^%$
    - name: Start the container
      docker:
        insecure_registry: true
        image: registry.d2t.vn/laravel-ansible-docker:{{DOCKER_TAG}}
        state: reloaded
        pull: always
        ports:
          - "8080:80"